In [1]:
import torch

## get divice

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


## get information about tensor

In [3]:
my_tensor = torch.tensor([[1,2,3],[2,5,6]], device=device,
                                            dtype=torch.float32,
                                            requires_grad=True)

print(my_tensor)

tensor([[1., 2., 3.],
        [2., 5., 6.]], device='cuda:0', requires_grad=True)


In [4]:
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.requires_grad)
print(my_tensor.shape)
print(my_tensor.ndim)
print(my_tensor.unique())
print(my_tensor.numel())

torch.float32
cuda:0
True
torch.Size([2, 3])
2
tensor([1., 2., 3., 5., 6.], device='cuda:0', grad_fn=<Unique2Backward0>)
6


## create tensor and vector

In [5]:
# 内存里存的是什么 就是什么
x = torch.empty((3,4))
x = torch.ones((3,4))
x = torch.zeros((3,4))
x = torch.eye(3)
x = torch.rand((3, 4)) # uniform 0-1
x = torch.randn((3, 4)) # normal distribution

x

tensor([[-0.3401, -1.6002, -0.1423, -0.4935],
        [ 0.4301, -0.6436, -1.4340,  0.0108],
        [ 0.2146,  0.8408,  0.9863, -0.3718]])

In [6]:
x = torch.randn((3,4))
print(x)
# choose the diag of given matrix
print(torch.diag(x,diagonal=0))
print(torch.diag(x,diagonal=1))

# get a square matrix where the given vector is its diag
x = torch.rand((4,))
print(x)
print(torch.diag(x,diagonal=0))


tensor([[ 2.0407, -0.1745,  0.7820,  0.3975],
        [-1.3017, -0.5491,  0.2158,  0.8316],
        [-0.0971, -0.4589,  1.0497,  0.3306]])
tensor([ 2.0407, -0.5491,  1.0497])
tensor([-0.1745,  0.2158,  0.3306])
tensor([0.0877, 0.9065, 0.3014, 0.2502])
tensor([[0.0877, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.9065, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.3014, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.2502]])


In [7]:
# init vector
x = torch.arange(start=5, end=10, step=7)
print(x)

# in linespace, step define the len of tensor
x = torch.linspace(start=0, end = 1, steps=60)
print(x.shape) 

tensor([5])
torch.Size([60])


In [8]:
x = torch.empty(3, 4)
print(x)

# make the matrix to the given mean and std
y = x.normal_(mean=1,std=0.1) 
print(y)
print(torch.mean(y),torch.std(y))

y = x.uniform_(2, 4) # make the matrix into uniform distr 
print(y.mean())

tensor([[1.0529e+03, 4.5720e-41, 3.4704e-08, 3.0721e-41],
        [       nan, 0.0000e+00, 1.7443e+28, 7.2326e+11],
        [2.7253e+20, 1.7728e+28, 1.4226e-13, 6.2608e+22]])
tensor([[0.8728, 0.9680, 0.8959, 0.9163],
        [1.0748, 1.0244, 0.9948, 1.2441],
        [1.0633, 1.0853, 0.9128, 1.1133]])
tensor(1.0138) tensor(0.1088)
tensor(2.8219)


## dtypes of tensor 

In [9]:
# convert tensor typr
my_tensor = torch.randn((3,4))

print(my_tensor.bool().dtype)
print(my_tensor.short().dtype)
print(my_tensor.long().dtype)
print(my_tensor.half().dtype)
print(my_tensor.float().dtype)
print(my_tensor.double().dtype)

torch.bool
torch.int16
torch.int64
torch.float16
torch.float32
torch.float64


## convert between tensor and numpy

In [10]:
# read tentor from np or convert tentor to np
import numpy as np
x = np.arange(4)
tentor = torch.from_numpy(x)
x = tentor.numpy()

## basic computation

In [11]:
# basic math
x = torch.arange(0,4)
y = torch.arange(4,8)
# element wise
print(x, y)
print(x + y)
print(x - y)
print(x * y)
print(x / y)

tensor([0, 1, 2, 3]) tensor([4, 5, 6, 7])
tensor([ 4,  6,  8, 10])
tensor([-4, -4, -4, -4])
tensor([ 0,  5, 12, 21])
tensor([0.0000, 0.2000, 0.3333, 0.4286])


In [12]:
# dot product between vectors
print(torch.dot(x, y)) 

tensor(38)


## Matrix computation

In [13]:
x = torch.rand((3,4))
y = torch.rand((4, 5))
# matrix mutiple
print(torch.mm(x, y))

x =  torch.rand((3,3))
# matrix power( three matrix mutiple, so it has to be square)
print(x.matrix_power(3))

tensor([[1.9517, 1.6379, 1.7771, 1.6023, 1.7179],
        [0.8889, 0.8461, 0.9744, 0.8472, 0.9397],
        [0.7846, 0.9553, 0.9314, 0.7398, 0.8064]])
tensor([[1.4201, 1.0848, 1.8519],
        [0.9973, 0.7317, 1.3530],
        [0.5393, 0.4708, 0.9267]])


In [14]:
batch_size = 8
m = 3
n = 4
p = 5
x = torch.rand((batch_size,m,n))
y = torch.rand((batch_size,n,p))
# mutiple in each sample
print(torch.bmm(x,y).shape)

torch.Size([8, 3, 5])


In [15]:
# boardcasting , operation between matrix and vector
x = torch.rand((3, 4))
y = torch.rand((1, 4))
print(x, y)
print(x - y)

tensor([[0.7316, 0.9577, 0.5964, 0.2414],
        [0.2626, 0.2511, 0.5810, 0.1232],
        [0.3198, 0.6263, 0.8598, 0.4782]]) tensor([[0.1181, 0.6759, 0.9828, 0.1383]])
tensor([[ 0.6135,  0.2818, -0.3864,  0.1031],
        [ 0.1445, -0.4248, -0.4017, -0.0151],
        [ 0.2018, -0.0496, -0.1230,  0.3399]])


## other computation

In [16]:
x = torch.randn((3,4))
print(x)
values, indices = torch.max(x, dim=0)
values, indices = torch.min(x, dim=1)
print(values, indices)
max_value = torch.max(x)
print(max_value)

# argmin return the second value in max
max_idx = torch.argmax(x, dim=0)
min_idx = torch.argmin(x, dim=1)
print(min_idx)

# for 2d tensor without specific dim
print(torch.argmax(x))  

tensor([[-0.2366,  1.5313, -2.0233,  0.1216],
        [-1.8623, -0.8286, -1.6883,  0.1865],
        [-0.8206, -1.2529, -0.7821, -0.4210]])
tensor([-2.0233, -1.8623, -1.2529]) tensor([2, 0, 1])
tensor(1.5313)
tensor([2, 0, 1])
tensor(1)


In [17]:
abs_x = torch.abs(x)
sum_x = torch.sum(x, dim=1)
print(abs_x, sum_x)

tensor([[0.2366, 1.5313, 2.0233, 0.1216],
        [1.8623, 0.8286, 1.6883, 0.1865],
        [0.8206, 1.2529, 0.7821, 0.4210]]) tensor([-0.6070, -4.1926, -3.2766])


In [18]:
# if x < min; x = min . if x > max ; then x = max . else x = x 
torch.clamp(x, min=-0.2, max=0.4) 

tensor([[-0.2000,  0.4000, -0.2000,  0.1216],
        [-0.2000, -0.2000, -0.2000,  0.1865],
        [-0.2000, -0.2000, -0.2000, -0.2000]])

In [19]:
# you can choose return one value or two
values, indices = torch.sort(x, dim=0, descending=True )
values =  torch.sort(x, dim=0, descending=True )

In [20]:
# operation in bool type
x = torch.tensor([1,0,0,2], dtype=torch.bool)
print(x)
print(torch.sum(x))
# any element is ture return true else flase
print(x.any())
# all elements are true return true else flase
print(x.all())

tensor([ True, False, False,  True])
tensor(2)
tensor(True)
tensor(False)


## index matrix

In [21]:
batch_size = 16
feature = 4
samples = torch.randn((batch_size,feature))

print(samples[0])
print(samples[:, 0])
samples[0,0]=100

tensor([ 0.6143, -0.3435,  0.6780,  0.5277])
tensor([ 0.6143, -0.1837,  1.0896, -0.5210, -0.2020, -0.9115, -1.5047, -0.6422,
         0.6635,  0.0694, -0.0300,  0.0466,  0.0604, -1.1941,  2.4532, -0.5146])


In [22]:
# use one list to select in vector
x = torch.arange(0,10,2)
idx = [1,3,4]
print(x)
print(x[idx])

tensor([0, 2, 4, 6, 8])
tensor([2, 6, 8])


In [23]:
# use two lists to index 2d tensor
x = torch.randn((3,4))
row = [0, 0, 1]
col = [1, 3, 3]
print(x)
print(x[row,col])

tensor([[-1.1144, -1.2844,  0.4159, -0.6050],
        [ 2.0439,  0.6659, -0.6165,  0.8448],
        [ 0.0809, -1.5831, -1.3097,  0.1721]])
tensor([-1.2844, -0.6050,  0.8448])


In [24]:
filt = (x > 0) & (x < 1)
print(x[filt])

tensor([0.4159, 0.6659, 0.8448, 0.0809, 0.1721])


## reshape Matrix

In [25]:
# squeeze/unsqueeze  remove/ delete one dimension in tensor
x = torch.arange(10)
print(x.shape)
x = x.unsqueeze(dim=0)
print(x)
print(x.shape)
x = x.unsqueeze(dim=-1)
print(x)
print(x.shape)
print(x.squeeze(0).shape)
print(x.squeeze(-1).shape)

torch.Size([10])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 10])
tensor([[[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]])
torch.Size([1, 10, 1])
torch.Size([10, 1])
torch.Size([1, 10])


In [26]:
# reshape tentor
x = torch.randn((3, 4))
x1 = x.reshape((2,6))
x2 = x.view(2,6)
print(x1 == x2)

tensor([[True, True, True, True, True, True],
        [True, True, True, True, True, True]])


In [27]:
# concate tensor in specific dim
x1 = torch.randn((2, 5))
x2 = torch.randn((2,5))
print(torch.cat([x1, x2], dim=0).shape)
print(torch.cat([x1, x2], dim=1).shape)

torch.Size([4, 5])
torch.Size([2, 10])


In [28]:
x1 = torch.randn((2, 5, 3))
# stretch x into vector
print(x1.view(-1).shape) 
# reshape into (2, X)
print(x1.view(2, -1).shape)

torch.Size([30])
torch.Size([2, 15])


In [29]:
# switch the 1, 2 axia
z = x1.permute(0, 2, 1)
print(z.shape)

torch.Size([2, 3, 5])
