In [1]:
import numpy as np

In [37]:
np.random.seed(5)
# weight W:(d,h) (3,4)
W=np.random.randn(3,4)
# input X:(N,d) (8,3)
X=np.random.randn(8,3)

print(f'------   W {W.shape}   --------\n',W)

print(f'------   X {X.shape}   --------\n',X)

------   W (3, 4)   --------
 [[ 0.44122749 -0.33087015  2.43077119 -0.25209213]
 [ 0.10960984  1.58248112 -0.9092324  -0.59163666]
 [ 0.18760323 -0.32986996 -1.19276461 -0.20487651]]
------   X (8, 3)   --------
 [[-0.35882895  0.6034716  -1.66478853]
 [-0.70017904  1.15139101  1.85733101]
 [-1.51117956  0.64484751 -0.98060789]
 [-0.85685315 -0.87187918 -0.42250793]
 [ 0.99643983  0.71242127  0.05914424]
 [-0.36331088  0.00328884 -0.10593044]
 [ 0.79305332 -0.63157163 -0.00619491]
 [-0.10106761 -0.05230815  0.24921766]]


In [38]:
## numeric gradient to W11
W_1=W.copy()
W_1[0][0]-=1e-5
print(W_1)
W_2=W.copy()
W_2[0][0]+=1e-5
print(W_2)

[[ 0.44121749 -0.33087015  2.43077119 -0.25209213]
 [ 0.10960984  1.58248112 -0.9092324  -0.59163666]
 [ 0.18760323 -0.32986996 -1.19276461 -0.20487651]]
[[ 0.44123749 -0.33087015  2.43077119 -0.25209213]
 [ 0.10960984  1.58248112 -0.9092324  -0.59163666]
 [ 0.18760323 -0.32986996 -1.19276461 -0.20487651]]


In [39]:
y=X@W
print(f'------   y {y.shape}   --------\n',y)
y_1=X@W_1
print(f'------   y_1 {y_1.shape}   --------\n',y_1)
y_2=X@W_2
print(f'------   y_2 {y_2.shape}   --------\n',y_2)

------   y (8, 4)   --------
 [[-4.04498466e-01  1.62287193e+00  5.64773843e-01  7.44980961e-02]
 [ 1.65706837e-01  1.44104517e+00 -4.96421575e+00 -8.85219000e-01]
 [-7.80057528e-01  1.84393630e+00 -3.09001360e+00  2.00344568e-01]
 [-5.52897554e-01 -9.56852538e-01 -7.86120647e-01  8.18403573e-01]
 [ 5.28840674e-01  7.78191103e-01  1.70381556e+00 -6.84806444e-01]
 [-1.79815149e-01  1.60356528e-01 -7.59765855e-01  1.11344672e-01]
 [ 2.79528272e-01 -1.25980434e+00  2.50936562e+00  1.75007619e-01]
 [-3.57325981e-03 -1.31545823e-01 -4.95369977e-01  5.36692478e-03]]
------   y_1 (8, 4)   --------
 [[-4.04494878e-01  1.62287193e+00  5.64773843e-01  7.44980961e-02]
 [ 1.65713839e-01  1.44104517e+00 -4.96421575e+00 -8.85219000e-01]
 [-7.80042416e-01  1.84393630e+00 -3.09001360e+00  2.00344568e-01]
 [-5.52888985e-01 -9.56852538e-01 -7.86120647e-01  8.18403573e-01]
 [ 5.28830710e-01  7.78191103e-01  1.70381556e+00 -6.84806444e-01]
 [-1.79811516e-01  1.60356528e-01 -7.59765855e-01  1.11344672e-01]

In [33]:
np.random.seed(4)
dy=np.random.randn(8,4)
print(f'------   dy {dy.shape}   --------\n',dy)

------   dy (8, 4)   --------
 [[ 0.05056171  0.49995133 -0.99590893  0.69359851]
 [-0.41830152 -1.58457724 -0.64770677  0.59857517]
 [ 0.33225003 -1.14747663  0.61866969 -0.08798693]
 [ 0.4250724   0.33225315 -1.15681626  0.35099715]
 [-0.60688728  1.54697933  0.72334161  0.04613557]
 [-0.98299165  0.05443274  0.15989294 -1.20894816]
 [ 2.22336022  0.39429521  1.69235772 -1.11281215]
 [ 1.63574754 -1.36096559 -0.65122583  0.54245131]]


In [44]:
dW11=np.sum(dy*((y_2-y_1)/(2*1e-5)))
##W11 影响y中的每一个元素  y中的每一个元素影响loss
print(dW11)

0.7587558750125036


In [43]:
## anyl gradient
dW=X.T@dy
print(dW[0][0])

0.7587558750166433


In [45]:
## cal relative error
print(f'relative error {abs((dW11-dW[0][0])/max(dW11,dW[0][0]))}')

relative error 5.45589000128535e-12


In [46]:
dW11_=np.sum(dy*((y_2-y)/(1e-5)))
##W11 影响y中的每一个元素  y中的每一个元素影响loss
print(dW11_)

0.7587558750040366


In [47]:
## cal relative error
print(f'relative error {abs((dW11_-dW[0][0])/max(dW11_,dW[0][0]))}')

relative error 1.661495334931619e-11
